name: Publish

on:
  push:
    branches: ['main']

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:

      - uses: actions/setup-go@v5

      - uses: actions/checkout@v4

      - uses: ko-build/setup-ko@v0.7

      - run: ko build ./cmd
