name: Publish

on:
  push:
    branches: ['main']

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    permissions:
        contents: read
        packages: write
        attestations: write
        id-token: write

    steps:

    - uses: actions/setup-go@v5

    - uses: actions/checkout@v4

    - uses: ko-build/setup-ko@v0.7

    - run: |
        image_digest=$(ko build ./cmd | cut -d\@ -f2)
        echo "Image digest: ${image_digest}"
        echo "IMAGE_DIGEST=${image_digest}" >> $GITHUB_ENV

    # - name: Get image digest
    #   run: |
    #     image_digest=$(docker inspect -f '{{ .Digest }}' my-image | tr -d '"')
    #     echo "Image digest: ${image_digest}"
    #     echo "IMAGE_DIGEST=${image_digest}" >> $GITHUB_ENV

    - uses: actions/attest-build-provenance@v1
      with:
        subject-name: ${{ env.KO_DOCKER_REPO }}
        subject-digest: ${{ env.IMAGE_DIGEST }}
        push-to-registry: true
